### ISSUE TITLE
Content column shows type and type column shows IN

### ISSUE THREAD

**Issue by jahlives** [Uberspace/dino#83]
Setup dino (docker based) today to interact with our pdns server (PowerDNS Authoritative Server 4.4.1, mysql based). Seems to me that the API response is parsed wrongly into the table in GUI as content column always shows the type and type column always show IN

This is the api response for one zone 

> {"comments": [], "name": "ourdomain.tld", "records": [{"content": "IP.ADDR", "disabled": false}], "ttl": 3600, "type": "A"}

Type | Name | Content | TTL |  
IN | ourdomain.tld. | A | 3600

**Comment by luto** [comment]
Dino uses the [`.../zones/{id}/export` endpoint](https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones-zone_id-export) instead of [`.../zones/{id}?rrsets=true`](https://doc.powerdns.com/authoritative/http-api/zone.html#get--servers-server_id-zones-zone_id), because it's much, much faster. What does the format of that endpoint look like on your pdns server?

**Comment by jahlives** [comment]
Wow that is fast response :-) 
export endpoint gives me like that

ourdomain.tld.	3600	IN	A	IP.ADDR

**Comment by luto** [comment]
Our pdns responds with:
```
adam.jonaspasche.com.	3600	A	82.98.87.122
```
well, so they added an `IN` to the output in some version?

**Comment by jahlives** [comment]
looks like, I do not have older versions to verify where the change happend. What pdns_server version do you use on your side?

**Comment by luto** [comment]
take this for a spin: https://github.com/Uberspace/dino/commit/9651964b79dfa75338cca31c947b73174e90bb37

**Comment by jahlives** [comment]
I hot patched the file and docker-compose up --build nad it works like charm :+1:
